version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "marcransome"
    groups:
      version-updates:
        applies-to: "version-updates"
        patterns:
          - "*"
      security-updates:
        applies-to: "security-updates"
        patterns:
          - "*"
